version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "octodash-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1euoqli1b71z4"
s3_prefix = "octodash-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
